############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# Config comment style borrowed from the Essentials config.
#
# If you want to use special characters (ASCII, UTF-8 characters) in the config, you need to save the file as UTF-8.
#   - If you don't know how this is done, you can see the guide on the wiki: https://github.com/Puharesource/TitleManager/wiki/Unicode---UTF-8-characters-for-TitleManager
#
# Config errors, such as the plugin not loading or the config resetting can be fixed by ensuring that:
#   - No tabs are present: YAML only allows spaces.
#   - You have escaped all apostrophes or quotes in your text:
#      - If you surround your text with apostrophes like this 'don't', double all of your apostrophes like this: 'don''t'
#      - If you surround your text with quotes like this "Quote: "hello"", switch to apostrophes instead like this 'Quite: "hello"'.
#
# If you've got problems:
#   - Join the Discord server here: https://discord.gg/U3Yyu6G
#   - Write a ticket on the Issue Tracker here: https://github.com/Puharesource/TitleManager/issues
#
# Help with animations and scripts:
# - Go to https://tarkan.dev/tmgenerator
#
# 1 second = 20 ticks
#
# For more information check: https://github.com/Puharesource/TitleManager/wiki

############################################################
# +------------------------------------------------------+ #
# |                       General                        | #
# +------------------------------------------------------+ #
############################################################

# Never change this value
config-version: 7

# Toggles debug mode, which prints additional information when the plugin does something.
debug: false

# Toggles whether or not all of the features of TitleManager will be toggled.
using-config: true

# Toggles whether or not all of the BungeeCord functionality will be toggled.
using-bungeecord: false

# (Feature only works on 1.7-1.8 Protocol Hack)
# Toggles whether or not 1.7 players will see actionbar messages when they're holding an item.
legacy-client-support: false

# Toggles whether or not the plugin should warn administrators if there's a new version out.
check-for-updates: true

# The locale used for some of the placeholders.
locale: 'en-US'

############################################################
# +------------------------------------------------------+ #
# |                     Player List                      | #
# +------------------------------------------------------+ #
############################################################

# Sets the header and footer of the player list. (Shown when you hold the TAB key.)

player-list:

  # Toggles this feature.
  enabled: true

  # Sets the header of the player list.
  #
  # Single line format.
  # header: 'My header text'
  #
  # Multiple line format.
  # header:
  # - 'My first line'
  # - 'My second line'
  # - 'My third line'
  header:
  - ''
  - '${shine:[0;2;0][0;25;0][0;25;0][&3;&b]My Server}'
  - ''

  # Sets the footer of the player list.
  #
  # Single line format.
  # footer: 'My footer text'
  #
  # Multiple line format.
  # footer:
  # - 'My first line'
  # - 'My second line'
  # - 'My third line'
  footer:
  - ''
  - '&7World time: &b%{12h-world-time}'
  - '&7Server time: &b%{server-time}'
  - ''
  - '${right-to-left} &b%{online}&7/&b%{max} &7Online Players ${left-to-right}'

############################################################
# +------------------------------------------------------+ #
# |                    Welcome Title                     | #
# +------------------------------------------------------+ #
############################################################

# Sets the title that is sent to the player when they join the server.

welcome-title:

  # Toggles this feature.
  enabled: true

  # The title shown.
  title: 'Welcome to My Server'

  # The subtitle shown.
  subtitle: 'Hope you enjoy your stay'

  # The time it takes for the title to fade into the screen. (In ticks)
  fade-in: 20

  # The time it takes for the title to stay on the screen. (In ticks)
  stay: 40

  # The time it takes for the title to fade out of the screen. (In ticks)
  fade-out: 20

  # The time it takes for the titles to appear. (In ticks)
  delay: 20

  # The title shown when the player joins the server for the first time.
  first-join:

    # The title shown.
    title: 'Welcome to My Server'

    # The subtitle shown.
    subtitle: 'This is your first time!'

############################################################
# +------------------------------------------------------+ #
# |                  Welcome Actionbar                   | #
# +------------------------------------------------------+ #
############################################################

# Sets the actionbar that is sent to the player when they join the server.

welcome-actionbar:

  # Toggles this feature.
  enabled: true

  # The message shown.
  title: 'Welcome to My Server'

  # The time it takes for the message to appear. (In ticks)
  delay: 20

  # The message shown when the player joins the server for the first time.
  first-join: 'Welcome to My Server, this is your first time!'

############################################################
# +------------------------------------------------------+ #
# |                     Placeholders                     | #
# +------------------------------------------------------+ #
############################################################

# Configures anything placeholder related.

placeholders:

  # The format used by the balance placeholder.
  number-format:

    # Toggles this feature.
    enabled: true

    # The format used.
    format: '#,###.##'

  # The format used by the server-time placeholder.
  # The format used can be found here: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
  date-format: 'EEE, dd MMM yyyy HH:mm:ss z'

############################################################
# +------------------------------------------------------+ #
# |                      Scoreboard                      | #
# +------------------------------------------------------+ #
############################################################

# Sets the scoreboard (sidebar) that is sent to the player

scoreboard:

  # Toggles this feature
  enabled: true

  # The title displayed at the very top of the scoreboard
  # WARNING! (1.12 or below ONLY) The title must consist of 32 or less characters (this includes color codes)
  title: '${shine:[0;2;0][0;25;0][0;25;0][&3&l;&b&l]My Server}'

  # The lines of the scoreboard (Maximum of 15 lines allowed)
  lines:
  - '&b&m----------------------------------'
  - '&b> &3&lPlayer Name:'
  - '&b%{name}'
  - '&r'
  - '&b> &3&lPing:'
  - '&b%{ping} MS'
  - '&r&r'
  - '&b> &3&lServer Time:'
  - '&b%{server-time}'
  - '&b&m----------------------------------&r'

  # A list of worlds that the Scoreboard should not be shown in.
  disabled-worlds:
  - 'my-disabled-world'
  - 'my-disabled-world-nether'

############################################################
# +------------------------------------------------------+ #
# |                      Announcer                       | #
# +------------------------------------------------------+ #
############################################################

# Automatically send titles and/or actionbar messages to the players on the server.

announcer:

  # Toggles this feature.
  enabled: true

  # The announcements
  #
  # The format:
  #
  # announcement-name:
  #   interval: 60                        (Seconds, Default: 60)
  #   timings:
  #     fade-in: 20                       (Ticks, Default: 20)
  #     stay: 40                          (Ticks, Default: 40)
  #     fade-out: 20                      (Ticks, Default: 20)
  #   titles:
  #   - 'First title'                     (The title sent)
  #   - 'Second title\nSecond subtitle'   (The next title sent, this time using \n to split the title and subtitle from each other)
  #   actionbar:
  #   - 'First actionbar'                 (The actionbar message sent)
  #   - 'The next actionbar sent'         (The next actionbar message sent)
  announcements:
    my-announcement:
      interval: 60
      timings:
        fade-in: 20
        stay: 40
        fade-out: 20
      titles:
      - '&aThis is the 1st title announcement\n&aThis is the subtitle'
      - '&bThis is the 2nd title announcement\n&bThis is the subtitle'
      actionbar:
      - '&aThis is the 1st actionbar announcement'
      - '&bThis is the 2nd actionbar announcement'

############################################################
# +------------------------------------------------------+ #
# |                       Bandwidth                      | #
# +------------------------------------------------------+ #
############################################################

# Configures all of the bandwidth saving options.

bandwidth:
  # Prevents sending identical packets, lowering bandwidth (but might be more CPU intensive).
  prevent-duplicate-packets: true

  # The tick rate of the player list in milliseconds. (Lower = More bandwidth & CPU usage, Higher = Less bandwidth & CPU usage)
  player-list-ms-per-tick: 50

  # The tick rate of the scoreboard in milliseconds. (Lower = More bandwidth & CPU usage, Higher = Less bandwidth & CPU usage)
  scoreboard-ms-per-tick: 50

############################################################
# +------------------------------------------------------+ #
# |                     Plugin Hooks                     | #
# +------------------------------------------------------+ #
############################################################

# Allows you to enable and disable certain hooks.

hooks:
  combatlogx: true

############################################################
# +------------------------------------------------------+ #
# |                       Messages                       | #
# +------------------------------------------------------+ #
############################################################

# Configures all of the messages sent to the users.

messages:
  # The message shown when a player doesn't have permission to run a command.
  no-permission: '&cYou do not have permission to run that command!'

  # The messages from the command /tm version
  command-version:
    description: 'Gives you the current running version of TitleManager'
    version: '&aThe server is running %version'

  # The messages from the command /tm reload
  command-reload:
    description: 'Reloads TitleManager'
    reloaded: '&aTitleManager reloaded'

  # The messages from the command /tm animations
  command-animations:
    description: 'Displays all loaded animations'
    format: '&aLoaded animations (&f%count&a): %animations'
    separator: '&f, &a'

  # The messages from the command /tm scripts
  command-scripts:
    description: 'Displays all loaded scripts'
    format: '&aLoaded scripts (&f%count&a): %scripts'
    separator: '&f, &a'

  # The messages from the command /tm broadcast
  command-broadcast:
    description: 'Broadcasts a title to the server'
    usage: '<title>|<title\nsubtitle>'
    title-sent: '&aYou have broadcasted the title "&r%title&a".'
    subtitle-sent: '&aYou have broadcasted the subtitle "&r%subtitle&a".'
    both-sent: '&aYou have broadcasted the titles "&r%title&a" "&r%subtitle&a".'

  # The messages from the command /tm abroadcast
  command-abroadcast:
    description: 'Broadcasts an actionbar title to the server'
    usage: '<title>'
    sent: '&aYou have broadcasted the actionbar title "&r%title&a".'

  # The messages from the command /tm message
  command-message:
    description: 'Sends a title to the specified player'
    usage: '<player> <title>|<title\nsubtitle>'
    title-sent: '&aYou have sent %player the title "&r%title&a".'
    subtitle-sent: '&aYou have sent %player the subtitle "&r%subtitle&a".'
    both-sent: '&aYou have sent %player the titles "&r%title&a" "&r%subtitle&a".'
    invalid-player: '&c%player is not a valid player.'

  # The messages from the command /tm amessage
  command-amessage:
    description: 'Sends an actionbar title to the specified player'
    usage: '<player> <title>'
    sent: '&aYou have sent %player the actionbar title "&r%title&a".'
    invalid-player: '&c%player is not a valid player.'

  # The messages from the command /tm scoreboard
  command-scoreboard:
    description: 'Toggles the scoreboard on or off.'
    usage: 'toggle'
    toggled-on: '&aYou have enabled your scoreboard.'
    toggled-off: '&cYou have disabled your scoreboard.'
